name: Coverage Comparison Action
description: 'Compares coverage and updates database.'
inputs:
  action_time:
    description: 'This action time'
    required: true
  ut_cases:
    description: 'These failed ut cases'
    required: true
    default: ''
  pr_link:
    description: 'This pr link'
    required: true
  job_time:
    description: 'This job time'
    required: true
  mo_host:
    description: 'This mo host'
    required: true
  mo_port:
    description: 'This mo port'
    required: true
  mo_user:
    description: 'This mo user'
    required: true
  mo_password:
    description: 'This mo password'
    required: true
  mo_database:
    description: 'This mo datavase Name'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'