name: "assign-issue"
description: "assign-issue"
inputs:
  GITHUB_TOKEN:
    description: "GitHub Token"
    required: true
    default: ""
  Issue_ID:
    description: "Issue ID"
    required: true
    default: ""
  GITHUB_REPOSITORY_OWNER:
    description: "github-repo-owner"
    required: true
    default: ""
  GITHUB_REPOSITORY:
    description: "github-repo"
    required: true
    default: ""
runs:
  using: "node20"
  main: "dist/index.js"