---
root: true
env:
    node: true
    jest: true
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: 2020
    sourceType: module
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/eslint-recommended
    - plugin:@typescript-eslint/recommended
    - plugin:import/errors
    - plugin:import/warnings
    - plugin:import/typescript
    - plugin:prettier/recommended
    - prettier/@typescript-eslint
plugins:
    - '@typescript-eslint'
    - 'jest'
rules:
    no-console: off
    linebreak-style:
        - error
        - unix
    prefer-const: error
