name: 'build-test'

on: [pull_request, push]

jobs:
    build_and_test:
        name: '${{ matrix.os }}: build and test'
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-latest
                    - macos-latest
                    - windows-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - run: |
                  npm install
              name: build
            - uses: symbitic/install-cmake@master
              name: validation test by running install-cmake
            - run: |
                  which cmake
                  cmake --version
              shell: bash
